### ISSUE TITLE
<g:paginate> tag is not working with grails 2.4.2

### ISSUE THREAD

**Issue by vikasi** [benorama/grails-fbootstrapp#1]
We are using fbootstrapp:0.1.1 and Grails 2.4.2. All GSPs having <g:paginate> tag are failing with below error.

Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:paginate>: null

Caused by: java.lang.StackOverflowError
 at grails.plugins.fboostrapp.FbootstrappTagLib$_closure1.doCall(FbootstrappTagLib.groovy:33)
 at grails.plugins.fboostrapp.FbootstrappTagLib$_closure1.doCall(FbootstrappTagLib.groovy:36)

As per our analysis this plugin is looking for tag definations at org.codehaus.groovy.grails.plugins.web.taglib.RenderTagLib (supported in 2.3.4) which is not supported in Grails 2.4.2.

**Comment by benorama** [comment]
Sorry, this plugin is not maintained anymore (we are now running on Grails3).
You might want to fork it?
